# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_message_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='handle',
            field=models.TextField(blank=True, default='Anonimous', null=True),
        ),
    ]
