# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-30 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20170226_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image_url',
            field=models.URLField(blank=True, default='http://www.gravatar.com/avatar/00000000000000000000000000000000?d=mm', max_length=500, null=True),
        ),
    ]
