# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-31 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='label',
            field=models.TextField(default=None),
        ),
    ]
