# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-01 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_member_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='label',
            field=models.SlugField(unique=True),
        ),
    ]
