# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-04 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20170801_0023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'Приватная группа'},
        ),
        migrations.AlterField(
            model_name='member',
            name='label',
            field=models.SlugField(unique=True, verbose_name='Название комнаты'),
        ),
    ]
