# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-05 23:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_auto_20170905_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberaccept',
            name='acceptroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acceptroom', to='chat.Room'),
        ),
    ]
